In [30]:
#as long the sheet has more than one column, then it is called data frame.

In [69]:
import numpy as np 
import pandas as pd

# Creating a dataframe

In [32]:
mydata = np.random.randint(0,101,(4,3))#(4,3) 4 is row 3 is column
my_index = ['CA', 'NY', 'AZ', 'TX']
my_col = ['Jan', 'Feb', 'May']#col is short for column
df = pd. DataFrame(data=mydata, index=my_index, columns=my_col)#df is short for data frame
df

    Jan  Feb  May
CA   82   31    8
NY   71    3   59
AZ   18   53   45
TX   75    5    6

# Read .csv file

In [33]:
df = pd.read_csv('tips.csv')
df
#it shows the first 5 and last 5 rows so it wont show it all because it could be way too long
#in 244 rows and 11 columns, it does not include the title row or the index column

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251
...,...,...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052842,Sat2657
240,27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,Monica Sanders,3506806155565404,Sat1766
241,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6011891618747196,Sat3880
242,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950,Sat17
243,18.78,3.00,Female,No,Thur,Dinner,2,9.39,Michelle Hardin,3511451626698139,Thur672

# Assignment1

In [34]:
#read the nba csv file

In [35]:
#explain the details of the features

In [36]:
#write the description of our dataset (objective truth)

In [37]:
#according to the study of our dataset, propose at least two topics that I can research through our dataset

# data frame: obtain basic information

In [38]:
df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size',
       'price_per_person', 'Payer Name', 'CC Number', 'Payment ID'],
      dtype='object')

In [39]:
len(df.columns)

11

In [40]:
df.index

RangeIndex(start=0, stop=244, step=1)

In [41]:
df.head(10)
#asking for the first 10

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251
5,25.29,4.71,Male,No,Sun,Dinner,4,6.32,Erik Smith,213140353657882,Sun9679
6,8.77,2.00,Male,No,Sun,Dinner,2,4.38,Kristopher Johnson,2223727524230344,Sun5985
7,26.88,3.12,Male,No,Sun,Dinner,4,6.72,Robert Buck,3514785077705092,Sun8157
8,15.04,1.96,Male,No,Sun,Dinner,2,7.52,Joseph Mcdonald,3522866365840377,Sun6820
9,14.78,3.23,Male,No,Sun,Dinner,2,7.39,Jerome Abbott,3532124519049786,Sun3775

In [42]:
df.tail(10)
#asking for the last 10

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
234,15.53,3.00,Male,Yes,Sat,Dinner,2,7.76,Tracy Douglas,4097938155941930,Sat7220
235,10.07,1.25,Male,No,Sat,Dinner,2,5.04,Sean Gonzalez,3534021246117605,Sat4615
236,12.60,1.00,Male,Yes,Sat,Dinner,2,6.30,Matthew Myers,3543676378973965,Sat5032
237,32.83,1.17,Male,Yes,Sat,Dinner,2,16.42,Thomas Brown,4284722681265508,Sat2929
238,35.83,4.67,Female,No,Sat,Dinner,3,11.94,Kimberly Crane,676184013727,Sat9777
239,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052842,Sat2657
240,27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,Monica Sanders,3506806155565404,Sat1766
241,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6011891618747196,Sat3880
242,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950,Sat17
243,18.78,3.00,Female,No,Thur,Dinner,2,9.39,Michelle Hardin,3511451626698139,Thur672

In [43]:
len(df)#gives you the number of rows

244

# selection and indexing

In [ ]:
df['smoker'].head(20)#grabbing a single column

0     No
1     No
2     No
3     No
4     No
5     No
6     No
7     No
8     No
9     No
10    No
11    No
12    No
13    No
14    No
15    No
16    No
17    No
18    No
19    No
Name: smoker, dtype: object

In [45]:
type(df['total_bill'])

pandas.core.series.Series

In [46]:
#grabbing multiple columns
df[['smoker','total_bill']]

    smoker  total_bill
0       No       16.99
1       No       10.34
2       No       21.01
3       No       23.68
4       No       24.59
..     ...         ...
239     No       29.03
240    Yes       27.18
241    Yes       22.67
242     No       17.82
243     No       18.78

[244 rows x 2 columns]

# Creating a new feature

In [47]:
df['tip_percentage'] = 100

In [48]:
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,tip_percentage
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959,100
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608,100
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458,100
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260,100
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251,100

In [49]:
df['tip_percentage'] = 100* df['tip'] / df['total_bill']

In [50]:
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,tip_percentage
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959,5.944673
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608,16.054159
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458,16.658734
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260,13.978041
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251,14.680765

# Adjusting existing columns

In [51]:
df['price_per_person'] = np.round(df['price_per_person'],1)

# How to remove a column

In [52]:
df = df.drop('tip_percentage',axis=1)

In [53]:
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.5,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.4,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.0,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.8,Nathaniel Harris,4676137647685994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.2,Tonya Carter,4832732618637221,Sun2251

# Set Index

In [54]:
df.set_index('Payment ID')

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number
Payment ID,,,,,,,,,,
Sun2959,16.99,1.01,Female,No,Sun,Dinner,2,8.5,Christy Cunningham,3560325168603410
Sun4608,10.34,1.66,Male,No,Sun,Dinner,3,3.4,Douglas Tucker,4478071379779230
Sun4458,21.01,3.50,Male,No,Sun,Dinner,3,7.0,Travis Walters,6011812112971322
Sun5260,23.68,3.31,Male,No,Sun,Dinner,2,11.8,Nathaniel Harris,4676137647685994
Sun2251,24.59,3.61,Female,No,Sun,Dinner,4,6.2,Tonya Carter,4832732618637221
...,...,...,...,...,...,...,...,...,...,...
Sat2657,29.03,5.92,Male,No,Sat,Dinner,3,9.7,Michael Avila,5296068606052842
Sat1766,27.18,2.00,Female,Yes,Sat,Dinner,2,13.6,Monica Sanders,3506806155565404
Sat3880,22.67,2.00,Male,Yes,Sat,Dinner,2,11.3,Keith Wong,6011891618747196
Sat17,17.82,1.75,Male,No,Sat,Dinner,2,8.9,Dennis Dixon,4375220550950
Thur672,18.78,3.00,Female,No,Thur,Dinner,2,9.4,Michelle Hardin,3511451626698139

# Reset Index

In [55]:
df = df.reset_index()

In [56]:
df.head()

,index,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,0,16.99,1.01,Female,No,Sun,Dinner,2,8.5,Christy Cunningham,3560325168603410,Sun2959
1,1,10.34,1.66,Male,No,Sun,Dinner,3,3.4,Douglas Tucker,4478071379779230,Sun4608
2,2,21.01,3.50,Male,No,Sun,Dinner,3,7.0,Travis Walters,6011812112971322,Sun4458
3,3,23.68,3.31,Male,No,Sun,Dinner,2,11.8,Nathaniel Harris,4676137647685994,Sun5260
4,4,24.59,3.61,Female,No,Sun,Dinner,4,6.2,Tonya Carter,4832732618637221,Sun2251

# Grabbing a single row

In [57]:
df.iloc[0]

index                                0
total_bill                       16.99
tip                               1.01
sex                             Female
smoker                              No
day                                Sun
time                            Dinner
size                                 2
price_per_person                   8.5
Payer Name          Christy Cunningham
CC Number             3560325168603410
Payment ID                     Sun2959
Name: 0, dtype: object

# Grabbing Multiple rows

In [58]:
df.iloc[0:4]

,index,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,0,16.99,1.01,Female,No,Sun,Dinner,2,8.5,Christy Cunningham,3560325168603410,Sun2959
1,1,10.34,1.66,Male,No,Sun,Dinner,3,3.4,Douglas Tucker,4478071379779230,Sun4608
2,2,21.01,3.50,Male,No,Sun,Dinner,3,7.0,Travis Walters,6011812112971322,Sun4458
3,3,23.68,3.31,Male,No,Sun,Dinner,2,11.8,Nathaniel Harris,4676137647685994,Sun5260

# Remove a row

# Conditional Filter

## Single Condition

In [59]:
bool_series = df['tip'] > 5
bool_series

0      False
1      False
2      False
3      False
4      False
       ...
239     True
240    False
241    False
242    False
243    False
Name: tip, Length: 244, dtype: bool

In [62]:
df[bool_series]

,index,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
23,23,39.42,7.58,Male,No,Sat,Dinner,4,9.9,Lance Peterson,3542584061609808,Sat239
44,44,30.40,5.60,Male,No,Sun,Dinner,4,7.6,Todd Cooper,503846761263,Sun2274
47,47,32.40,6.00,Male,No,Sun,Dinner,4,8.1,James Barnes,3552002592874186,Sun9677
52,52,34.81,5.20,Female,No,Sun,Dinner,4,8.7,Emily Daniel,4291280793094374,Sun6165
59,59,48.27,6.73,Male,No,Sat,Dinner,4,12.1,Brian Ortiz,6596453823950595,Sat8139
85,85,34.83,5.17,Female,No,Thur,Lunch,4,8.7,Shawna Cook,6011787464177340,Thur7972
88,88,24.71,5.85,Male,No,Thur,Lunch,2,12.4,Roger Taylor,4410248629955,Thur9003
116,116,29.93,5.07,Male,No,Sun,Dinner,4,7.5,Shawn Blake,4689079711213722,Sun22
141,141,34.30,6.70,Male,No,Thur,Lunch,6,5.7,Steven Carlson,3526515703718508,Thur1025
155,155,29.85,5.14,Female,No,Sun,Dinner,5,6.0,Madison Wilson,4210875236164664,Sun9176
170,170,50.81,10.00,Male,Yes,Sat,Dinner,3,16.9,Gregory Clark,5473850968388236,Sat1954
172,172,7.25,5.15,Male,Yes,Sun,Dinner,2,3.6,Larry White,30432617123103,Sun9209
181,181,23.33,5.65,Male,Yes,Sun,Dinner,2,11.7,Jason Cox,6556931703586223,Sun3402
183,183,23.17,6.50,Male,Yes,Sun,Dinner,4,5.8,Dr. Michael James,4718501859162,Sun6059
211,211,25.89,5.16,Male,Yes,Sat,Dinner,4,6.5,Christopher Li,6011962464150569,Sat6735
212,212,48.33,9.00,Male,No,Sat,Dinner,4,12.1,Alex Williamson,676218815212,Sat4590
214,214,28.17,6.50,Female,Yes,Sat,Dinner,3,9.4,Marissa Jackson,4922302538691962,Sat3374
239,239,29.03,5.92,Male,No,Sat,Dinner,3,9.7,Michael Avila,5296068606052842,Sat2657

In [65]:
df[df['tip'] > 5]
#this is the prefered way to filter out

,index,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
23,23,39.42,7.58,Male,No,Sat,Dinner,4,9.9,Lance Peterson,3542584061609808,Sat239
44,44,30.40,5.60,Male,No,Sun,Dinner,4,7.6,Todd Cooper,503846761263,Sun2274
47,47,32.40,6.00,Male,No,Sun,Dinner,4,8.1,James Barnes,3552002592874186,Sun9677
52,52,34.81,5.20,Female,No,Sun,Dinner,4,8.7,Emily Daniel,4291280793094374,Sun6165
59,59,48.27,6.73,Male,No,Sat,Dinner,4,12.1,Brian Ortiz,6596453823950595,Sat8139
85,85,34.83,5.17,Female,No,Thur,Lunch,4,8.7,Shawna Cook,6011787464177340,Thur7972
88,88,24.71,5.85,Male,No,Thur,Lunch,2,12.4,Roger Taylor,4410248629955,Thur9003
116,116,29.93,5.07,Male,No,Sun,Dinner,4,7.5,Shawn Blake,4689079711213722,Sun22
141,141,34.30,6.70,Male,No,Thur,Lunch,6,5.7,Steven Carlson,3526515703718508,Thur1025
155,155,29.85,5.14,Female,No,Sun,Dinner,5,6.0,Madison Wilson,4210875236164664,Sun9176
170,170,50.81,10.00,Male,Yes,Sat,Dinner,3,16.9,Gregory Clark,5473850968388236,Sat1954
172,172,7.25,5.15,Male,Yes,Sun,Dinner,2,3.6,Larry White,30432617123103,Sun9209
181,181,23.33,5.65,Male,Yes,Sun,Dinner,2,11.7,Jason Cox,6556931703586223,Sun3402
183,183,23.17,6.50,Male,Yes,Sun,Dinner,4,5.8,Dr. Michael James,4718501859162,Sun6059
211,211,25.89,5.16,Male,Yes,Sat,Dinner,4,6.5,Christopher Li,6011962464150569,Sat6735
212,212,48.33,9.00,Male,No,Sat,Dinner,4,12.1,Alex Williamson,676218815212,Sat4590
214,214,28.17,6.50,Female,Yes,Sat,Dinner,3,9.4,Marissa Jackson,4922302538691962,Sat3374
239,239,29.03,5.92,Male,No,Sat,Dinner,3,9.7,Michael Avila,5296068606052842,Sat2657

In [66]:
df[df['sex'] == 'Male']

,index,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
1,1,10.34,1.66,Male,No,Sun,Dinner,3,3.4,Douglas Tucker,4478071379779230,Sun4608
2,2,21.01,3.50,Male,No,Sun,Dinner,3,7.0,Travis Walters,6011812112971322,Sun4458
3,3,23.68,3.31,Male,No,Sun,Dinner,2,11.8,Nathaniel Harris,4676137647685994,Sun5260
5,5,25.29,4.71,Male,No,Sun,Dinner,4,6.3,Erik Smith,213140353657882,Sun9679
6,6,8.77,2.00,Male,No,Sun,Dinner,2,4.4,Kristopher Johnson,2223727524230344,Sun5985
...,...,...,...,...,...,...,...,...,...,...,...,...
236,236,12.60,1.00,Male,Yes,Sat,Dinner,2,6.3,Matthew Myers,3543676378973965,Sat5032
237,237,32.83,1.17,Male,Yes,Sat,Dinner,2,16.4,Thomas Brown,4284722681265508,Sat2929
239,239,29.03,5.92,Male,No,Sat,Dinner,3,9.7,Michael Avila,5296068606052842,Sat2657
241,241,22.67,2.00,Male,Yes,Sat,Dinner,2,11.3,Keith Wong,6011891618747196,Sat3880
242,242,17.82,1.75,Male,No,Sat,Dinner,2,8.9,Dennis Dixon,4375220550950,Sat17

# Multiple - Condition

In [67]:
df[(df['total_bill'] > 30) & (df['sex'] == 'Male')]

,index,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
23,23,39.42,7.58,Male,No,Sat,Dinner,4,9.9,Lance Peterson,3542584061609808,Sat239
39,39,31.27,5.00,Male,No,Sat,Dinner,3,10.4,Mr. Brandon Berry,6011525851069856,Sat6373
44,44,30.40,5.60,Male,No,Sun,Dinner,4,7.6,Todd Cooper,503846761263,Sun2274
47,47,32.40,6.00,Male,No,Sun,Dinner,4,8.1,James Barnes,3552002592874186,Sun9677
56,56,38.01,3.00,Male,Yes,Sat,Dinner,4,9.5,James Christensen DDS,349793629453226,Sat8903
59,59,48.27,6.73,Male,No,Sat,Dinner,4,12.1,Brian Ortiz,6596453823950595,Sat8139
83,83,32.68,5.00,Male,Yes,Thur,Lunch,2,16.3,Daniel Murphy,5356177501009133,Thur8801
95,95,40.17,4.73,Male,Yes,Fri,Dinner,4,10.0,Aaron Bentley,180026611638690,Fri9628
112,112,38.07,4.00,Male,No,Sun,Dinner,3,12.7,Jeff Lopez,3572865915176463,Sun591
141,141,34.30,6.70,Male,No,Thur,Lunch,6,5.7,Steven Carlson,3526515703718508,Thur1025
142,142,41.19,5.00,Male,No,Thur,Lunch,5,8.2,Eric Andrews,4356531761046453,Thur3621
156,156,48.17,5.00,Male,No,Sun,Dinner,6,8.0,Ryan Gonzales,3523151482063321,Sun7518
167,167,31.71,4.50,Male,No,Sun,Dinner,4,7.9,Michael Lawson,3566285921227119,Sun3719
170,170,50.81,10.00,Male,Yes,Sat,Dinner,3,16.9,Gregory Clark,5473850968388236,Sat1954
173,173,31.85,3.18,Male,Yes,Sun,Dinner,2,15.9,Scott Perez,3577115550328507,Sun9335
175,175,32.90,3.11,Male,Yes,Sun,Dinner,2,16.4,Nathan Reynolds,370307040837149,Sun5109
179,179,34.63,3.55,Male,Yes,Sun,Dinner,2,17.3,Brian Bailey,346656312114848,Sun9851
180,180,34.65,3.68,Male,Yes,Sun,Dinner,4,8.7,James Hebert DDS,676168737648,Sun7544
182,182,45.35,3.50,Male,Yes,Sun,Dinner,3,15.1,Jose Parsons,4112207559459910,Sun2337
184,184,40.55,3.00,Male,Yes,Sun,Dinner,2,20.3,Stephen Cox,3547798222044029,Sun5140
187,187,30.46,2.00,Male,Yes,Sun,Dinner,5,6.1,David Barrett,4792882899700988,Sun9987
207,207,38.73,3.00,Male,Yes,Sat,Dinner,4,9.7,Ricky Ramirez,347817964484033,Sat4505
210,210,30.06,2.00,Male,Yes,Sat,Dinner,3,10.0,Shawn Mendoza,30184049218122,Sat8361
212,212,48.33,9.00,Male,No,Sat,Dinner,4,12.1,Alex Williamson,676218815212,Sat4590
237,237,32.83,1.17,Male,Yes,Sat,Dinner,2,16.4,Thomas Brown,4284722681265508,Sat2929

In [68]:
df[(df['day'] == 'Sun') | (df['day'] == 'Sat')]

,index,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,0,16.99,1.01,Female,No,Sun,Dinner,2,8.5,Christy Cunningham,3560325168603410,Sun2959
1,1,10.34,1.66,Male,No,Sun,Dinner,3,3.4,Douglas Tucker,4478071379779230,Sun4608
2,2,21.01,3.50,Male,No,Sun,Dinner,3,7.0,Travis Walters,6011812112971322,Sun4458
3,3,23.68,3.31,Male,No,Sun,Dinner,2,11.8,Nathaniel Harris,4676137647685994,Sun5260
4,4,24.59,3.61,Female,No,Sun,Dinner,4,6.2,Tonya Carter,4832732618637221,Sun2251
...,...,...,...,...,...,...,...,...,...,...,...,...
238,238,35.83,4.67,Female,No,Sat,Dinner,3,11.9,Kimberly Crane,676184013727,Sat9777
239,239,29.03,5.92,Male,No,Sat,Dinner,3,9.7,Michael Avila,5296068606052842,Sat2657
240,240,27.18,2.00,Female,Yes,Sat,Dinner,2,13.6,Monica Sanders,3506806155565404,Sat1766
241,241,22.67,2.00,Male,Yes,Sat,Dinner,2,11.3,Keith Wong,6011891618747196,Sat3880
242,242,17.82,1.75,Male,No,Sat,Dinner,2,8.9,Dennis Dixon,4375220550950,Sat17